### ISSUE TITLE
App Launcher Unable to run Java

### ISSUE THREAD

**Issue by whammond4** [OpenTravel/OTM-DE-Utilities#1]
The app launcher is unable to open any of the listed applications, citing that the system cannot find Java under the path specified in the system environment variable. The path environment variable is configured to be `C:\Program Files\Java\jre1.8.0_231` which includes the Java executable, as outlined in the below screenshots.

![image](https://user-images.githubusercontent.com/58559896/71986122-e82b7000-31f9-11ea-9b8b-1b63a1dc3c5f.png)

![image](https://user-images.githubusercontent.com/58559896/71986338-5112e800-31fa-11ea-83a0-87cf659e260f.png)

**Comment by xmldave** [comment]
Sent email. There is nothing obvious wrong with the code and it runs on several different computers. 
Please assure java runs from your command line.
